Update 921-160 to address false positives
DataDog/appsec-event-rules pull request #125
Opened 2023-02-10 14:03 UTC by Taiki-San

### What does this PR do?

### Motivation

### Checklist
- [ ] Did you added the `test_vectors` for your rules
- [ ] Did you tested it on your local machine first
- [ ] Did you tested it on staging

### Additional Notes

2023-02-10 14:11 UTC, vdeturckheim approved these changes

2023-02-13 08:59 UTC, vdeturckheim requested changes

2023-02-13 08:59 UTC, vdeturckheim commented on build/recommended.json
> -            "regex": "[\\n\\r]+(?:\\s|location|refresh|(?:set-)?cookie|(?:x-)?(?:forwarded-(?:for|host|server)|host|via|remote-ip|remote-addr|originating-IP))\\s*:",
we still need to catch `set-cookie        :`. do we?

2023-02-13 09:09 UTC, Taiki-San commented on build/recommended.json
> -            "regex": "[\\n\\r]+(?:\\s|location|refresh|(?:set-)?cookie|(?:x-)?(?:forwarded-(?:for|host|server)|host|via|remote-ip|remote-addr|originating-IP))\\s*:",
We do

2023-02-13 09:10 UTC, vdeturckheim approved these changes

2023-02-14 11:02 UTC, merged