init
DataDog/appsec-event-rules pull request #52
Opened 2022-02-22 08:20 UTC by netcode

### What does this PR do?
Add another job to the CI to test on old libraries versions

2022-02-22 09:53 UTC, cbeauchesne requested changes

2022-02-22 09:53 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
not a branch anymore on github. Maybe @simon-id will know how to install this version using npm ?

2022-02-22 09:53 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        run: touch binaries/${{ matrix.version }}
You need to load the `tar.gz` yourself, https://github.com/DataDog/dd-trace-dotnet/releases is probably the way to go

2022-02-22 09:53 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        run: touch binaries/${{ matrix.version }}
Same, you need to load it on https://github.com/DataDog/dd-trace-java/releases

2022-02-22 09:53 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +on:
You may want to add a nightly schedule

2022-02-22 15:57 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
`npm install <whatever install an old version of the tracer with appsec>`

2022-02-22 16:52 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
yep it's "working" : https://github.com/DataDog/appsec-event-rules/runs/5289792912?check_suite_focus=true#step:7:91

This version was not respecting schemas, I nned to update the system test to skip this test for this version

2022-02-22 16:58 UTC, cbeauchesne commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
Mmmmh, actually all appsec test are failing, are you sure this line enables appsec ?

2022-02-23 10:19 UTC, netcode commented on .github/workflows/system-tests-old-versions.yaml
> +        run: touch binaries/${{ matrix.version }}
@cbeauchesne I updated the binary and now it's loaded but I got failure appsec tests too.
https://github.com/DataDog/appsec-event-rules/runs/5301362171?check_suite_focus=true#step:7:378
cc @robertpi

2022-02-23 12:19 UTC, netcode commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
Thanks @simon-id  for help. Do you know why the test is still failing ??

2022-02-23 19:45 UTC, simon-id commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
Well, as this is the absolute first version of appsec in nodejs, are you sure the system tests existed when I released this version ? Was it ever meant to pass system tests ? I'm not sure myself...
What's the point of running the tests on such an old version anyway ? It's way past deprecated

2022-02-24 08:07 UTC, netcode commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
@simon-id  the idea is to make sure every time we release a rules version it will work on old versions **used by customers** 

I updated the versions to the public beta version and it works. Just wanted to check if any customers used older version ?

2022-02-24 10:01 UTC, simon-id commented on .github/workflows/system-tests-old-versions.yaml
> +        version: [DataDog/dd-trace-js#2.0.0-appsec-alpha.1]
I don't think I have a way to tell which versions are used sadly, but yes I think `beta.1` is a more relevant version to test.
The alpha version has been downloaded 17 times this week, and 70% of it is probably caused by this PR.
The oldest version with non negligible use (>100 downloads a week) is `2.0.0-appsec-beta.5` and the version after that is `2.0.0`. For now let's keep `beta.1` like you did, and if we get failures at some point, I don't mind bumping this to `2.0.0`.

2022-02-24 13:50 UTC, cbeauchesne approved these changes

2022-02-24 13:52 UTC, merged